### ISSUE TITLE
Is the mixing of DESCENDING and ASCENDING data allowed?

### ISSUE THREAD

**Issue by Since-r** [adugnag/gee_s1_ard#10]
Hi,
I'm sorry to bother you again.
Will the mixed use of DESCENDING and ASCENDING data cause any problems?
I've seen a lot of research clearly marked the type of orbital used.
And heard that they can not be mixed due to the difference of backscattering coefficient.
Is that true?
Thanks!!!

**Comment by adugnag** [comment]
Yes, different orbits should be processed separately.
