### ISSUE TITLE
Problem with helper.py function

### ISSUE THREAD

**Issue by gaowudao** [adugnag/gee_s1_ard#11]
Tank you for your work!

I want to use the python api, but imagecollection.map(helper.lin_to_db)  or imagecollection.map(helper.lin_to_db2) got the non valve  in VV and VH. 
here is my code:

parameter = {'START_DATE': startdate,
            'STOP_DATE': enddate,        
            'POLARIZATION': 'VVVH',
            'ORBIT' : 'BOTH',
            #'ORBIT_NUM': None,
            'ROI': geometry,
            'APPLY_BORDER_NOISE_CORRECTION': True,
            'APPLY_SPECKLE_FILTERING': True,
            'SPECKLE_FILTER_FRAMEWORK':'MULTI',
            'SPECKLE_FILTER': 'BOXCAR',
            'SPECKLE_FILTER_KERNEL_SIZE': 50,
            'SPECKLE_FILTER_NR_OF_IMAGES':50,
            'APPLY_TERRAIN_FLATTENING': True,
            'DEM': ee.Image('USGS/SRTMGL1_003'),
            'TERRAIN_FLATTENING_MODEL': 'VOLUME',
            'TERRAIN_FLATTENING_ADDITIONAL_LAYOVER_SHADOW_BUFFER':0,
            'FORMAT': 'DB',
            'CLIP_TO_ROI': True,
            'SAVE_ASSET': False,
            'ASSET_ID': "users/mraj"
            }
#processed s1 collection
s1_processed = wp.s1_preproc(parameter)

visparam = {}
if parameter.get('POLARIZATION')=='VVVH':
    if parameter.get('FORMAT')=='DB':
        s1_preprocces_view = s1_processed.map(helper.add_ratio_lin).map(helper.lin_to_db2)
        visparam = {'bands':['VV', 'VH', 'VVVH_ratio'], 'min': [-20,  -25,  0], 'max': [0, -5, 0.7]}
    else:
        s1_preprocces_view = s1_processed.map(helper.add_ratio_lin)
        visparam = {'bands':['VV', 'VH', 'VVVH_ratio'], 'min': [0.01,  0.0032,  0], 'max': [1, 0.31, 0.7]}
else:
    if parameter.get('FORMAT')=='DB':
        s1_preprocces_view = s1_processed.map(helper.lin_to_db)
        visparam = {'bands':[parameter.POLARIZATION], 'min': -25, 'max': 0}
    else:
        s1_preprocces_view = s1_processed
        visparam = {'bands':[parameter.POLARIZATION], 'min': 0, 'max': 0.2}

Map.addLayer(s1_preprocces_view.first().clip(geometry), visparam, 'First image in the processed S1 collection');

#######
error:
######
EEException: Collection.first: Error in map(ID=S1A_IW_GRDH_1SDV_20200604T100319_20200604T100344_032866_03CE8D_F0CE):
Image.select: Pattern 'VV' did not match any bands.

**Comment by adugnag** [comment]
You should separately check platform A and B separately.
