### ISSUE TITLE
Multitemporal filter doesn't do anything (except singletemporal filtering)

### ISSUE THREAD

**Issue by FlashThunder** [adugnag/gee_s1_ard#12]
I did multitemporal lee filter on S1 collection (whole year) and it does nothing else than Lee filter itself.

**Comment by adugnag** [comment]
GEE resamples the output on the fly based on the viewing scale so visual comparison of different filters tend to look similar. If you want to visually compare, please reproject the output to a fixed scale first before using Map.addLayer().

**Comment by FlashThunder** [comment]
I have checked on huge zoom on one corner, and they are exactly the same.

**Comment by adugnag** [comment]
Then increase the kernel size and number of images in the multi-temporal speckle filter settings.

**Comment by FlashThunder** [comment]
I tried everything still ... only it does is lee filtering, but nothing more.

**Comment by adugnag** [comment]
please paste the parameter dictionary here so I can reproduce your results

**Comment by adugnag** [comment]
<img width="856" alt="Screen Shot 2022-06-08 at 9 08 00 PM" src="https://user-images.githubusercontent.com/48068921/172697274-e4a5350e-23f4-4cc9-a03a-4943e3128fd5.png">

This the Multi-temporal Lee filter with a 9x9 filter kernel and 10 images in the framework.

<img width="856" alt="Screen Shot 2022-06-08 at 9 08 00 PM" src="https://user-images.githubusercontent.com/48068921/172697553-b0511213-b3e7-4779-8798-9e5c525cb101.png">

Whereas this is the Multi-temporal boxcar filter with kernel size of 15 and number of images of 14.

<img width="852" alt="Screen Shot 2022-06-08 at 9 12 57 PM" src="https://user-images.githubusercontent.com/48068921/172698066-575a95ba-3e90-47ac-832d-e3c4e923b642.png">

Finally, the mono-temporal Lee filter with 9x9 filter kernel. From the three examples, it is pretty clear the multi-temporal filter is doing something.

**Comment by FlashThunder** [comment]
Maybe I am doing something wrong?

https://code.earthengine.google.com/82a2a95203ed1c8778dd71e8024197d4

**Comment by FlashThunder** [comment]
This is ho original data looks like:

![image](https://user-images.githubusercontent.com/16067512/173353762-b666ba14-a026-4342-89cd-306c94e7d3a9.png)

This is how the same image with 5 images multitemporal and lee kernel=7 looks like:

![image](https://user-images.githubusercontent.com/16067512/173353944-3eeb20a0-c36e-4426-8fe3-97ad4cd10e85.png)

And this is how LEE with kernel=7 looks like:

![image](https://user-images.githubusercontent.com/16067512/173354066-d5e8f461-044d-407f-824e-085d0297f3cd.png)

It does differ now, but I got like an opposite problem - multitemporal doesn't seem to apply LEE?

**Comment by adugnag** [comment]
But this is what I told you in previous posts. With 5 images in the multi-temporal filter, you're not doing much filtering. So I would suggest you increase your kernel size to 9x9 for Lee filter. And increase the number of images in the multi-temporal filter framework to a minimum of 10. It would be optimal if you can increasing it further (40). I hope this helpful.

**Comment by adugnag** [comment]
You can also implement the equivalent number of looks (ENL=mean^2/variance)  for a homogeneous region in your image to see if they are really identical or not.
