### ISSUE TITLE
bands not compatible when exporting

### ISSUE THREAD

**Issue by pleitebier** [adugnag/gee_s1_ard#14]
Hi, in GEE I tried to export S1 ARD images to my drive in configuration VVVH with DB values for a specific region. Unfortunately, I got for most of them (not all) the following error cause bands are not of the same type. 
![grafik](https://user-images.githubusercontent.com/116659061/197807285-f3647222-44d5-4389-ac44-29d35767e270.png)

VV and VH bands are in double, while angle and VVVH-ratio are float types. Where in the scripts would be the implementation of a band transformation most appropriate?

Thanks for your help.
Felix

**Comment by adugnag** [comment]
Hello,

Thank you for bringing this to my attention. Can you please forward your code snippet so I can try to reproduce your error?

Thanks,
Adugna

**Comment by pleitebier** [comment]
Hi Adugna,

thanks for responding. I found another solution meanwhile, but here is the code, which still reproduces the error:[https://code.earthengine.google.com/8a36b6f1eb97bf2dc29cbae2646750bd](url)

I basically copied your gee s1 ard code and appled it.

cheers
