### ISSUE TITLE
Problems downloading ImageCollection to asset

### ISSUE THREAD

**Issue by sniffadog001** [adugnag/gee_s1_ard#17]
So...am such a noob. I totally forgot to go to Tasks and run the downloads.......

Hi, your code is working well, unless I set download to true, at which point the page becomes unresponsive.
I wondered whether I am alone in this experience, or whether you could assist a relative newbie in overcoming this challenge. 
I m trying to map locations of small scale illegal artisanal mining in the Lower Zambezi region of Zambia where I live. I am hoping the SAR will be able to detect the locations of the mining sites. Much appreciated.

**Comment by adugnag** [comment]
Yes, this is common especially if you're downloading a lot of images. Usually you have to wait a bit until all the download tasks are loaded into the task window when using the code editor.

**Comment by adugnag** [comment]
Le me know if you get an error after waiting...

**Comment by sniffadog001** [comment]
Many thanks for your fast reply ! I am such a newbie to all this, I totally forgot I had to go to Tasks and Run the downloads....I know right. Anyway, many thanks for the code.
