### ISSUE TITLE
extra parameters when using python api: issues

### ISSUE THREAD

**Issue by bhyleee** [adugnag/gee_s1_ard#18]
Dear adugnag, thanks for creating this fantastic package!

I have no problem running the javascript api and incorporating it into my workflow on the GEE code editor. 

I am having issues running the same workflow over the same study area using the python api: I am running into issues around the extra parameters of orbit_num and platform number specifically. I noticed these are not required for the JS code but are required for the python. Can I just comment these out? I noticed there are no default values for these two?

Thanks!

**Comment by anfrinconal** [comment]
Hello
I'd like to know if you knew how to execute it. How did you do it? Thank you very much.@bhyleee 

Thanks @adugnag

**Comment by anfrinconal** [comment]
PLATFORM_NUMBER=='A' or PLATFORM_NUMBER=='B'

**Comment by bhyleee** [comment]
Yes I was hoping it would be a similar situation where the script would query for both A or B, but I eventually just select one or the other. Thanks
    "ORBIT": 'BOTH',
    "ORBIT_NUM": None,
    "PLATFORM_NUMBER": "A",

**Comment by adugnag** [comment]
Sorry for the very late response. I just updated the Python code so there shouldn't be anymore bugs.
