### ISSUE TITLE
Same parameters, different results in Code Editor and Python 

### ISSUE THREAD

**Issue by valeriallactayo** [adugnag/gee_s1_ard#19]
Hi there! I am attempting to implement the gee_s1_ard script on Google Colab. 

- While the script works correctly on Google Earth Engine Code Editor **(returning 57 available images for my ROI)**, when trying to run it on Google Colab with the same parameters, it indicates **no images available**. 
- In Code editor I've created a polygon while In python, I've imported a shapefile and then I've converted it into a ee.Geometry 

Result in Code editor:
![image](https://github.com/adugnag/gee_s1_ard/assets/75514994/de7d1b38-38a7-4fc7-85bf-7a643ab59542)

Result in Python:
![image](https://github.com/adugnag/gee_s1_ard/assets/75514994/f9061db2-c57e-46cf-b0bc-6acafa72a59a)

Geometry in python:
![image](https://github.com/adugnag/gee_s1_ard/assets/75514994/1a2af2b1-066e-487a-aa77-2955e4835b31)

Tt would help me a lot to know what mistake I am making.

Thanks in advance!

**Comment by adugnag** [comment]
Sorry for the late response. It's because you have extra parameters such as Orbit number in the Python code. Set the orbit number to None and try again. You should have similar results.
