### ISSUE TITLE
Correct link to the repo on GEE

### ISSUE THREAD

**Issue by mcgregorian1** [adugnag/gee_s1_ard#2]
Hi.

Unless I'm missing something, I'm clicking on the link to access the repo on Earth Engine (both of them in the README of this repo on GitHub), but it is taking me to a separate repo that does not have the function `s1_ard.js`. I instead see the repo below. Can you please advise?

![image](https://user-images.githubusercontent.com/39522449/124797453-4258de80-df20-11eb-957d-8c1fc79266ea.png)

**Comment by adugnag** [comment]
That is strange. The links in the readme point to https://code.earthengine.google.com/?accept_repo=users/adugnagirma/gee_s1_ard . Let me know if you can access it using this link.

**Comment by mcgregorian1** [comment]
Hm, unfortunately I'm not sure why but it takes me to the same (incorrect) repo. This probably is just an issue with my GEE; at any rate, I'm simply copying the source code from github and creating a new file as a workaround.
