### ISSUE TITLE
How to install the python packages in Colab

### ISSUE THREAD

**Issue by DAGIS-Bin** [adugnag/gee_s1_ard#20]
A simple question!
I want to use Python packages in Colab. When I installed the software package, the code indicated an error（As shown follows）. 
**How should I correct it?**
Thank you first
![image](https://github.com/adugnag/gee_s1_ard/assets/104047240/34741b42-14ad-4502-a434-ebe55b329f2b)

**Comment by adugnag** [comment]
Hi, these scripts are not installation packages. You have to download the folder and run the main scripts in your favorite Python or Javascript IDE.
