### ISSUE TITLE
Exclusion of Scenes only containing VV polarization

### ISSUE THREAD

**Issue by sberndtJPL** [adugnag/gee_s1_ard#23]
Greetings,

I am utilizing your python API to create a S1 ARD over the US West Coast. 

As a test case, I will limit the study period to be 01/01/2015 - 02/01/2015 with the Polarization configuration set to "VV"

Using [ASF Vertex](https://search.asf.alaska.edu/#/?polygon=POLYGON((-125.291%2048.254,-125.2997%2048.1632,-125.2913%2048.044,-125.2067%2047.72,-125.1701%2047.6391,-125.0722%2047.4832,-125.0069%2047.4091,-124.9057%2047.3311,-124.8726%2047.1722,-124.8324%2047.0642,-124.7563%2046.944,-124.7557%2046.8682,-124.738%2046.7619,-124.7045%2046.662,-124.6436%2046.5534,-124.6366%2046.4778,-124.6583%2046.2898,-124.6536%2046.1844,-124.6299%2046.0733,-124.5703%2045.9403,-124.5354%2045.6408,-124.5544%2045.4765,-124.5511%2045.2624,-124.5869%2045.1014,-124.636%2044.941,-124.6494%2044.8575,-124.6429%2044.6793,-124.6619%2044.4929,-124.6864%2044.3795,-124.6967%2044.1763,-124.7192%2044.0198,-124.7548%2043.8506,-124.7852%2043.7474,-124.8649%2043.6573,-124.9123%2043.5792,-124.9448%2043.5026,-124.97%2043.4037,-124.985%2043.26,-125.0956%2043.0431,-125.1204%2042.9506,-125.1303%2042.8551,-125.125%2042.7594,-125.1047%2042.6661,-125.0121%2042.4452,-125.0003%2042.2878,-124.9769%2042.131,-124.9535%2042.0486,-124.8217%2041.7869,-124.8076%2041.6584,-124.7777%2041.5664,-124.7378%2041.4885,-124.6754%2041.405,-124.7254%2041.276,-124.7407%2041.1777,-124.7348%2041.0493,-124.8938%2040.7811,-124.9715%2040.5724,-124.9857%2040.4851,-124.9861%2040.3969,-124.9729%2040.3098,-124.9387%2040.2105,-124.9181%2040.1006,-124.883%2040.0114,-124.839%2039.9374,-124.7767%2039.8632,-124.5195%2039.6661,-124.3844%2039.5407,-124.4028%2039.3871,-124.3912%2039.2457,-124.3459%2039.0889,-124.3083%2038.9978,-124.3079%2038.8977,-124.2907%2038.8079,-124.2624%2038.7301,-124.2028%2038.6196,-124.1582%2038.5592,-124.0147%2038.4195,-123.8212%2038.269,-123.7648%2038.1963,-123.6996%2038.1359,-123.5856%2038.0578,-123.5867%2037.9481,-123.5691%2037.8573,-123.5033%2037.7124,-123.4445%2037.6368,-123.3797%2037.5769,-123.3049%2037.527,-123.2218%2037.4885,-123.0894%2037.4511,-123.0488%2037.3063,-122.9952%2037.213,-122.9817%2037.125,-122.9458%2037.0143,-122.8964%2036.9109,-122.8057%2036.7995,-122.5482%2036.5731,-122.5367%2036.4736,-122.465%2036.2512,-122.4507%2036.1763,-122.4241%2036.0985,-122.3848%2036.0244,-122.333%2035.9558,-122.2146%2035.8401,-122.1407%2035.787,-122.0751%2035.7539,-121.9748%2035.6361,-121.9176%2035.5527,-121.8302%2035.4694,-121.7809%2035.3945,-121.6815%2035.2862,-121.5996%2035.2228,-121.5081%2035.1755,-121.4587%2035.1262,-121.4197%2035.019,-121.3782%2034.9507,-121.3252%2034.8876,-121.239%2034.8105,-121.2071%2034.7048,-121.2237%2034.5706,-121.1997%2034.4286,-121.1276%2034.2866,-121.0122%2034.1624,-121.032%2034.041,-121.0264%2033.9534,-120.9815%2033.811,-120.9391%2033.7397,-120.8838%2033.6737,-120.816%2033.6151,-120.7279%2033.5618,-120.5532%2033.4916,-120.4709%2033.4711,-120.3011%2033.3932,-120.1471%2033.3692,-120.1559%2033.2464,-120.1441%2033.1682,-120.1193%2033.0916,-120.0812%2033.0181,-120.0061%2032.9153,-119.945%2032.8532,-119.8794%2032.8043,-119.722%2032.7333,-119.562%2032.698,-119.4727%2032.6905,-119.3833%2032.6957,-119.2964%2032.7131,-119.151%2032.769,-119.0305%2032.6018,-118.8768%2032.4572,-118.7406%2032.362,-118.66%2032.3225,-118.5713%2032.2946,-118.4774%2032.2799,-118.3814%2032.2793,-118.2871%2032.293,-118.1239%2032.3419,-118.0395%2032.3826,-117.9657%2032.4338,-117.9037%2032.493,-117.8245%2032.6119,-117.7942%2032.503,-117.7584%2032.427,-117.7145%2032.3629,-117.6284%2032.279,-117.5425%2032.1732,-117.4684%2032.1145,-117.3905%2032.0708,-117.3036%2032.0381,-117.2101%2032.0184,-117.0694%2032.0149,-114.6307%2032.2026,-114.3531%2032.2632,-114.2712%2032.3002,-114.1986%2032.3471,-114.0067%2032.5307,-113.956%2032.6036,-113.9236%2032.6713,-113.9004%2032.7508,-113.8853%2032.8873,-113.8908%2032.9755,-113.928%2033.1244,-114.019%2033.299,-113.9717%2033.3981,-113.953%2033.4734,-113.9466%2033.5552,-113.9196%2033.6865,-113.9203%2033.7398,-113.7478%2033.8687,-113.6778%2033.9395,-113.6285%2034.0104,-113.5927%2034.0859,-113.5704%2034.1642,-113.5613%2034.2441,-113.5671%2034.37,-113.5838%2034.4481,-113.6134%2034.524,-113.656%2034.5962,-113.7447%2034.7036,-113.8076%2034.7587,-113.9007%2034.8194,-113.9692%2034.9661,-114.0629%2035.0853,-114.1101%2035.2299,-114.1619%2035.3126,-114.2542%2035.4077,-114.9309%2035.9516,-115.7266%2036.5767,-116.6412%2037.2775,-118.1543%2038.3941,-119.4269%2039.2932,-119.4179%2040.3211,-119.4209%2048.9995,-119.4425%2049.1756,-119.4776%2049.2817,-119.5266%2049.3769,-119.5865%2049.4588,-119.6473%2049.5201,-119.7199%2049.5743,-119.805%2049.618,-119.955%2049.6544,-122.7582%2049.6595,-122.8707%2049.6467,-122.9562%2049.6193,-123.0946%2049.536,-123.1959%2049.4411,-123.2876%2049.3343,-123.4%2049.3101,-123.4759%2049.2781,-123.5489%2049.2331,-123.6175%2049.1747,-123.6851%2049.0955,-123.7373%2049.0101,-123.7779%2048.9134,-123.8043%2048.809,-123.8725%2048.8097,-124.0907%2048.8877,-124.2386%2048.9174,-124.4817%2049.0112,-124.5796%2049.0351,-124.6562%2049.0405,-124.805%2049.0295,-124.8863%2049.01,-124.9656%2048.9769,-125.0417%2048.9297,-125.1127%2048.8681,-125.1764%2048.7922,-125.2301%2048.7027,-125.2709%2048.6014,-125.2961%2048.4914,-125.3038%2048.3771,-125.291%2048.254))&zoom=5.467&center=-119.433,35.204&start=2015-01-01T08:00:00Z&end=2015-02-02T07:59:59Z&productTypes=GRD_HD,GRD_HS&beamModes=IW&polarizations=VV%2BVH,VV,Dual%20VH,Dual%20VV&resultsLoaded=true&granule=S1A_IW_GRDH_1SSV_20150131T020211_20150131T020236_004409_005638_DF41-GRD_HS), I can see that there exists 75 files over the study area for this study period.

However, when I run your API with the same constraints it comes back with the following message, indicating 0 results:
```
Number of images in collection:  0
Additional border noise correction is completed
Multi-temporal speckle filtering is completed
Radiometric terrain normalization is completed
```

I noticed the wrapper.py script automatically filters the dataset based on the VH polarization, regardless of the provided configuration input for POLARIZATION. What I'm not sure about is why (e.g. is this a requirement to do the processing?). 

See below:

https://github.com/adugnag/gee_s1_ard/blob/42814d95ace58e50640e4b0a4139c3373e43de18/python-api/wrapper.py#L136

Note, this is similarly an issue for the javascript version as well: https://github.com/adugnag/gee_s1_ard/blob/42814d95ace58e50640e4b0a4139c3373e43de18/javascript/wrapper.js#L79

If I update this filter option in L136 of wrapper.py to rather be:
`        .filter(ee.Filter.listContains('transmitterReceiverPolarisation', POLARIZATION))\
`

and keep the polarization configuration set to "VV"

I get a more appropriate response of
`
Number of images in collection:  79
Additional border noise correction is completed
Multi-temporal speckle filtering is completed
Radiometric terrain normalization is completed
`

Note that the results differ by 4 when compared to ASF. Without digging, I would attribute this to the datasets not being the same, or one of the bounds are inclusive/exclusive. That's outside the scope of this issue.

That said, I believe this to be a bug given the following quote from your [manuscript](https://www.mdpi.com/2072-4292/13/10/1954#:~:text=in%20linear%20scale.-,Data%20can%20be%20selected%20in%20single%20polarization%20i.e.%2C,%F0%9D%91%89,-%E2%80%B2):

> Data can be selected in single polarization i.e., ′𝑉𝐻′ or ′𝑉𝑉′ or dual polarization mode i.e., ′𝑉𝑉′ and ′𝑉𝐻′

This bug is solvable as described above. PR incoming...

**Comment by sberndtJPL** [comment]
Unable to push a commit; please see fix therein.

**Comment by adugnag** [comment]
Hello, thank you for bringing this to my attention. The code was initially written to consider only dual-pol configurations (hence the filter ` .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH'))`, as the 'VH' polarization doesn't exist as a standalone single-pol data. So users were able to select 'VV', 'VH', and 'VV+VH' polarizations from the available dual-pol datasets. 

To accommodate users who use single-pol, i.e. 'VV' data, I have modified the wrapper script in both the JavaScript and Python codes to separate these cases.

```javascript
var s1 = ee.ImageCollection('COPERNICUS/S1_GRD_FLOAT')
      .filter(ee.Filter.eq('instrumentMode', 'IW'))
      .filter(ee.Filter.eq('resolution_meters', 10))
      .filterDate(params.START_DATE, params.STOP_DATE)
      .filterBounds(params.GEOMETRY);

if (params.POLARIZATION == 'VV') {
    s1 = s1.filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'));
} else {
    s1 = s1.filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH'));
}
