### ISSUE TITLE
Question about availability of VVVH

### ISSUE THREAD

**Issue by mcgregorian1** [adugnag/gee_s1_ard#3]
Hello,

I was trying out the code as written, and noticed I was getting the following error message below, which to me indicates that either 
- there is no VH available, which is odd considering the parameter `VVVH` means the ImageCollection is filtered to contain both bands, or
- the bands are being renamed incorrectly in the underlying scripts.

I tried changing the `wrapper` script such that it contained the following code but this did not solve the issue. Possibly this might be because there is a period of time for this point (Myanmar) where some data was not obtained, but I had thought adding this filtering process would mean dates were analyzed only if they contained observations for both polarizations.
```
if (params.POLARIZATION=='VV') { s1 = s1.select(['VV','angle'])}
  else if (params.POLARIZATION=='VH') {s1 = s1.select(['VH','angle'])}
  else if (params.POLARIZATION=='VVVH') {
    s1 = s1.filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))
            .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH'))
            .select(['VV', 'VH', 'angle'])}
  ```

![image](https://user-images.githubusercontent.com/39522449/125134321-14a89c80-e0bc-11eb-88b7-cf7974183656.png)

Can you please advise? Here is the set of parameters with my geometry.

```
var pt = ee.Geometry.Point([95.219623, 23.029892])
  
var wrapper = require('users/adugnagirma/gee_s1_ard:wrapper');
var helper = require('users/adugnagirma/gee_s1_ard:utilities');

//---------------------------------------------------------------------------//
// DEFINE PARAMETERS
//---------------------------------------------------------------------------//

var parameter = {//1. Data Selection
              START_DATE: "2015-06-23",
              STOP_DATE: "2020-02-01",
              POLARIZATION:'VVVH',
              ORBIT : 'BOTH',
              GEOMETRY: pt, //uncomment if interactively selecting a region of interest
              //GEOMETRY: ee.Geometry.Polygon([[[104.80, 11.61],[104.80, 11.36],[105.16, 11.36],[105.16, 11.61]]], null, false), //Uncomment if providing coordinates
              //GEOMETRY: ee.Geometry.Polygon([[[112.05, -0.25],[112.05, -0.45],[112.25, -0.45],[112.25, -0.25]]], null, false),
              //2. Additional Border noise correction
              APPLY_ADDITIONAL_BORDER_NOISE_CORRECTION: true,
              //3.Speckle filter
              APPLY_SPECKLE_FILTERING: true,
              SPECKLE_FILTER_FRAMEWORK: 'MULTI',
              SPECKLE_FILTER: 'REFINED LEE',
              SPECKLE_FILTER_KERNEL_SIZE: 7,
              SPECKLE_FILTER_NR_OF_IMAGES: 10,
              //4. Radiometric terrain normalization
              APPLY_TERRAIN_FLATTENING: true,
              DEM: ee.Image('USGS/SRTMGL1_003'),
              TERRAIN_FLATTENING_MODEL: 'VOLUME',
              TERRAIN_FLATTENING_ADDITIONAL_LAYOVER_SHADOW_BUFFER: 0,
              //5. Output
              FORMAT : 'DB',
              CLIP_TO_ROI: false,
              SAVE_ASSETS: false
}

//---------------------------------------------------------------------------//
// DO THE JOB
//---------------------------------------------------------------------------//
     
//Preprocess the S1 collection
var s1_preprocces = wrapper.s1_preproc(parameter);

var s1 = s1_preprocces[0]
s1_preprocces = s1_preprocces[1]


//---------------------------------------------------------------------------//
// EXPORT
//---------------------------------------------------------------------------//

//Convert format for export
if (parameter.FORMAT=='DB'){
  s1_preprocces = s1_preprocces.map(helper.lin_to_db);
}

print(s1_preprocces.first())
print(s1_preprocces)

//Save processed collection to asset
if(parameter.SAVE_ASSETS) {
helper.Download.ImageCollection.toAsset(s1_preprocces, '', 
               {scale: 10, 
               region: s1_preprocces.geometry(),
                type: 'float'})
}
```

**Comment by adugnag** [comment]
This means only single pol (VV) images are available for the specified roi and date in the GEE Sentinel-1 catalogue. I have seen this type of issues for some regions especially from the year 2014 to 2018. In your roi, you have both VV and VH polarizations starting 2018.

**Comment by mcgregorian1** [comment]
This is true for Descending, but I've noticed that using the two orbits together there is full coverage.

For context, I had developed a script earlier that manually did speckle filtering (only Refined Lee) plus the Vollrath et al 2020 correction, then I extracted the VV / VH values at a point for every date that had both VV and VH readings (see below plot). I'm confused why I'm able to do this but I'm not able to use your module and get the same result. I've also tried running Ascending and Descending separately (in the code I wrote in the original post) but I also received the same errors.

For the record, the below plot refers to a different point than the original post. However, I have run this script on ~200 points and have gotten measurements just as seen here.
```
var pt = ee.Geometry.Point([97.90212, 23.17163]) 
```

![image](https://user-images.githubusercontent.com/39522449/125298250-d3db9e00-e2dc-11eb-98c7-5e13c80e2a74.png)

**Comment by adugnag** [comment]
The problem arises when we call the sentinel-1 images  from line 76 to 81. The VH channel is a dual-pol mode in Sentinel-1 unlike the VV pol, so we have to add an additional filter s1.filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH')) to make sure all the images have a VV and VH band. 

I hope this solves your problem.

**Comment by mcgregorian1** [comment]
I guess overall I'm just confused as to why when I extract band values on my own, I can get a full time series, but your module does not allow me to even though we are both doing the same filtering. 

Here is a subset of my script when it calls the S1 data - note how `filtered` contains images from 2015 onward that contain both VV and VH, for both Ascending and Descending orbits.

I tried getting "S1_GRD_FLOAT" as you did and my code ran correctly. 

```
var pt = ee.Geometry.Point([97.90212, 23.17163]) 

var satellite = "COPERNICUS/S1_GRD"
var date_start = '2015-06-23';
var date_end = '2020-01-31';

  var satimgs_init = ee.ImageCollection(satellite)
                  .filterDate(date_start, date_end)
                  .filterBounds(pt);
                  
  // filter to keep VV and VH
  var filtered = satimgs_init.filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))
              .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH'))
              .filter(ee.Filter.eq('instrumentMode', 'IW'));
              
  print(filtered.first())
  print(filtered)
```

From your module:
```
/************************  
   * 1. Data Selection
  ************************/ 
  
  // Select S1 GRD ImageCollection
var s1 = ee.ImageCollection('COPERNICUS/S1_GRD_FLOAT')
      .filter(ee.Filter.eq('instrumentMode', 'IW'))
      .filter(ee.Filter.eq('resolution_meters', 10))
      .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VH'))
      .filterDate(params.START_DATE, params.STOP_DATE)
      .filterBounds(params.GEOMETRY);
```

**Comment by adugnag** [comment]
I see the same 226 images in both. Anyway, if you have other issues with the ARD framework I'll be happy to help.

**Comment by mcgregorian1** [comment]
Hi @adugnag apologies for not being clear. As you saw, both return the 226 images. However, my code successfully retrieves the VV-VH values for all of those, whereas your ARD code does not due to the error mentioned in the original post. My main issue is I do not understand why. Potentially it has to do with me trying to implement the mutli-temporal speckle filter + Refined Lee using your ARD framework, whereas in my original code I only do the Refined Lee.

**Comment by adugnag** [comment]
Well, the issue came from band inconsistencies between the image to be filtered and the dedicated collection that we call in speckle_filter.MultiTemporal_Filter. Its now solved by getting the last polarization from the image to be filtered, and then filtering for images that contain that (please see line 361 to 379). I hope this helps!

**Comment by mcgregorian1** [comment]
I see. Yes, I can confirm this works for the test point I used, thank you! I will attempt to use this for all my study points (~200) and I will confirm here if it works for batch-processing.

Final question: What is the purpose of line 105 in `s1_ard.js`? It seems that `var s1` is not used anywhere.

**Comment by adugnag** [comment]
That's just for visualizing the processed and raw images to help people select processing parameters. It is not important if you're not interested in visualizations.

**Comment by mcgregorian1** [comment]
I see. Also, I have tried batch-processing using the ARD framework and I can confirm it is working. Thank you for your help with this!
