### ISSUE TITLE
Problems in _correct function in terrain_flattening.py

### ISSUE THREAD

**Issue by marielaraj** [adugnag/gee_s1_ard#7]
Hi! I am using your library the python-API version. I find it very useful, thank you very much!

I think I found some indentation problems in wrapper.py and in terrain_flattening.py. Also, the function _correct in the terrain_flattening.py script was having some trouble. It seems that the reproject function was not calling the arguments properly. I fix them and made you a PR: https://github.com/adugnag/gee_s1_ard/pull/6
Thanks again!

**Comment by adugnag** [comment]
Thank you for solving the bugs. I have merged your PR with the main code.
