### ISSUE TITLE
How to implement speckle filtering only？

### ISSUE THREAD

**Issue by Since-r** [adugnag/gee_s1_ard#8]
Dear author:
    I want to use LEE filter on GEE, Sentinel-1's most commonly used filter.
    And I noticed you seem to use another filtering method.
    So how about this filter's performance?(compare with LEE filter) 
        And how can I use a filter only?
    Thanks for sharing! Looking forward to your repeat! :)

**Comment by adugnag** [comment]
In the params dictionary on the main script, set the parameters as               
SPECKLE_FILTER_FRAMEWORK: 'MONO',
SPECKLE_FILTER: 'LEE',

**Comment by Since-r** [comment]
Thanks for your directions!
There are other problems:
**1.** No matter which filter I use, the image will appear mosaic phenomenon and increase with the increase of the 'FILTER_KERNEL_SIZE'. And the improvement of the image seems to only eliminate some belts
**2.** When the 'FILTER_FRAMEWORK' is selected as "MULTI", there are obvious belts on the image
**3.** If I only focus on 'water and other' binary classification research, can I not load 'Radiometric terrain normalization'? (It's my personal confusion after seen your article)

**Comment by adugnag** [comment]
can you include some figures so I know what exactly the problem is?

**Comment by Since-r** [comment]
[(https://github.com/Since-r/GEE-SAR-filter.git)](url)

The belts of boxcar does not change with the window size

**Comment by Since-r** [comment]
https://github.com/Since-r/GEE-SAR-filter.git

The belts of boxcar does not change with the window size

**Comment by adugnag** [comment]
This is strange. Can you also send the geometry for your roi so I can try to reproduce your error?

**Comment by Since-r** [comment]
**Here is roi, part of the original location**
0: [36.1685295962306,6.445558767546823]
1: [37.6132317446681,6.445558767546823]
2: [37.6132317446681,7.786436891480829]
3: [36.1685295962306,7.786436891480829]
4: [36.1685295962306,6.445558767546823]

**And here is code I modified some places**
`var wrapper = require('users/adugnagirma/gee_s1_ard:wrapper');
var helper = require('users/adugnagirma/gee_s1_ard:utilities');

var parameter = {
              //1. Data Selection
              START_DATE: "2018-06",
              STOP_DATE: "2018-07",
              POLARIZATION:'VV',
              GEOMETRY: geometry, 
              //2. Additional Border noise correction
              APPLY_ADDITIONAL_BORDER_NOISE_CORRECTION: true,
              //3.Speckle filter
              APPLY_SPECKLE_FILTERING: true,
              SPECKLE_FILTER_FRAMEWORK: 'MULTI', // MONO
              SPECKLE_FILTER: 'BOXCAR', // LEE SIGMA  BOXCAR
              SPECKLE_FILTER_KERNEL_SIZE: 5,
              SPECKLE_FILTER_NR_OF_IMAGES: 6,
              //4. Radiometric terrain normalization
              APPLY_TERRAIN_FLATTENING: false,
              DEM: ee.Image('USGS/SRTMGL1_003'),
              TERRAIN_FLATTENING_MODEL: 'VOLUME',
              TERRAIN_FLATTENING_ADDITIONAL_LAYOVER_SHADOW_BUFFER: 0,
              //5. Output
              FORMAT : 'DB',
              CLIP_TO_ROI: true,
              SAVE: false
}


//---------------------------------------------------------------------------//
// MAIN
//---------------------------------------------------------------------------//
      
//Preprocess the S1 collection
var s1_preprocces = wrapper.s1_preproc(parameter);

var s1 = s1_preprocces[0] 
s1_preprocces = s1_preprocces[1] 


//---------------------------------------------------------------------------//
// VISUALIZE
//---------------------------------------------------------------------------//


if (parameter.FORMAT=='DB') {
  var Processed = s1_preprocces.map(helper.lin_to_db).median().select('VV')
  var Origin = s1.map(helper.lin_to_db).median().select('VV')
  var visparam = {bands:[parameter.POLARIZATION],min: -25,max: 0}   
}


Map.centerObject(parameter.GEOMETRY, 9);

Map.addLayer(Origin, visparam, 'Origin');
Map.addLayer(Processed, visparam, 'Processed');`

**Comment by adugnag** [comment]
The lines are a result of image collection reduction to derive the median image you're displaying (var Processed = s1_preprocces.map(helper.lin_to_db).median().select('VV')). This is because the images in the collection have different extents. This artefact has nothing to do with the speckle filtering or any other processing module you're using. To confirm this, you can set the border noise and speckle filtering to false and check if the artefact is there.

**Comment by Since-r** [comment]
However, when a sufficient imagecollection are used, belts will also occur.
So, how about Question1 ? **speckle filtering** does not denoise, but makes the image more blurred

**Comment by adugnag** [comment]
The belts are not the results of insufficient number of images but due to different image extents. This case maybe worse if the border noise in the images is not completely removed. 

As to your question why the images are blurred, it has to do with the type of filter selected, the 'MONO' filter framework and the selected kernel size. If you're interested in preserving resolution,  I suggest you use the 'MULTI' framework and select smaller kernel size.

**Comment by Since-r** [comment]
Thanks
In mono mode, the results of ARD is different from the LEE filter I used locally. What causes this? I really want to implement SAR denoising in this way

**Comment by adugnag** [comment]
Google earth engine displays layers at scale so what you see depends on your viewing scale. So the discrepancies between the GEE version of Lee filter and your local implementations are due to this. If you want to make comparisons with your local processing please reproject the GEE Lee output to a fixed resolution or download the processed data.

**Comment by Since-r** [comment]
I'm sorry to bother you again
When I change the speckle filter (REFINED LEE)，
GEE will report an error: Layer error: User memory limit exceeded；
    Even the image is calculated, it will be much slower than before

**Comment by adugnag** [comment]
refined Lee filter is computationally intensive so you may run into memory problems, especially if you retroject it to a fixed resolution. So to avoid that, exporting the data may be one solution.

**Comment by Since-r** [comment]
Thanks! But
it also appears in export, and another problem "Too many concurrent aggregations" in running.
I only used a small ROI (about 0.5x0.5), is that reasonable?
Does that mean I can not achieve it on a larger scale...

**Comment by adugnag** [comment]
Its quite common to be out of memory when reprojecting to a specific resolution. So my suggestion is if you export then don't reproject. The reprojection is only helpful for onscreen comparisons.
