### ISSUE TITLE
Problem with converting to decibels

### ISSUE THREAD

**Issue by dkhramov** [adugnag/gee_s1_ard#9]
Hi! Thank you very much for your work! Today I used JavaScript modules and found a strange result.

I’ve calculated sigma-nought in linear scale (‘LINEAR’) and converted it to decibels: db_scale = 10*log10(lin_scale). Then I’ve calculated sigma-nought in decibels (‘DB’) and the results didn't match. My script: https://code.earthengine.google.com/?scriptPath=users%2Fdakhramov%2Fpublic%3Atest_db

**Comment by adugnag** [comment]
Hi, Thank you for raising this but the two operations you compared are not the same. If you want to compare them, take a pixel value in linear scale (avoid the reducer), apply the formula and then compare it with the same pixel in the db image.

**Comment by luji1515** [comment]
Hello, thank you for your work! When I run s1_ard.js, I found some mistake, such as " First image in the processed S1 collection: Tile error: Reprojection output too large (11809x11041 pixels)."  The only change is that the study area has become larger.  Can you give me some advice.

**Comment by adugnag** [comment]
If you want to retroject, work with smaller images.
